### ISSUE TITLE
预训练文件存放路径应在checkpoints文件夹下

### ISSUE THREAD

**Issue by Ponhappy** [LeiaLi/SRDiff#13]
README中写的不太清晰，应该放在checkpoints/srdiff_pretrained_div2k/目录下的

**Comment by xiaodu-1** [comment]
> README中写的不太清晰，应该放在checkpoints/srdiff_pretrained_div2k/目录下的

你好，请问如何利用提供的预训练模型在随便的一张低分辨率图像上进行测试？期待您的回复，或者可以提供您的代码吗？谢谢

**Comment by d-linlin** [comment]
> README中写的不太清晰，应该放在checkpoints/srdiff_pretrained_div2k/目录下的

您好，请问您成功跑通代码了吗？您有遇到过这个报错吗ModuleNotFoundError: No module named 'utils';

**Comment by duanpanjun** [comment]
> > README中写的不太清晰，应该放在checkpoints/srdiff_pretrained_div2k/目录下的
> 
> 您好，请问您成功跑通代码了吗？您有遇到过这个报错吗ModuleNotFoundError: No module named 'utils';

你可以直接把utils这个文件夹直接放在报错代码的同级目录下

**Comment by pinkina** [comment]
> > > README中写的不太清晰，应该放在checkpoints/srdiff_pretrained_div2k/目录下的
> > 
> > 
> > 您好，请问您成功跑通代码了吗？您有遇到过这个报错吗ModuleNotFoundError: No module named 'utils';
> 
> 你可以直接把utils这个文件夹直接放在报错代码的同级目录下

你好，你有跑出来srdiff的代码吗？为什么我跑出来psnr的指标是90几呀，可以请教一下是哪里出了问题吗

**Comment by pinkina** [comment]
> README中写的不太清晰，应该放在checkpoints/srdiff_pretrained_div2k/目录下的

您好，论文中讲的celeba总共训练30k次，预训练模型直接就是30k次呢，所以这个是不用预训练模型还是把总训练次数改成60k次呀？

**Comment by xuxuduoduomeiGithub** [comment]
> > README中写的不太清晰，应该放在checkpoints/srdiff_pretrained_div2k/目录下的
> 
> 您好，论文中讲的celeba总共训练30k次，预训练模型直接就是30k次呢，所以这个是不用预训练模型还是把总训练次数改成60k次呀？

Traceback (most recent call last):
  File "D:\anaconda_path\envs\basicsr\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda_path\envs\basicsr\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\SRDiff-main\tasks\trainer.py", line 248, in <module>
    trainer.train()
  File "F:\SRDiff-main\tasks\trainer.py", line 57, in train
    model = self.build_model()
  File "F:\SRDiff-main\tasks\srdiff.py", line 13, in build_model
    hidden_size = hparams['hidden_size']
KeyError: 'hidden_size'
你好~你碰到这个问题了吗？可否请教一下？

**Comment by pinkina** [comment]
那celebA这个数据集就没有预训练模型，从头开始训练吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年1月7日(周二) 晚上9:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LeiaLi/SRDiff] 预训练文件存放路径应在checkpoints文件夹下 (Issue #13)




   
README中写的不太清晰，应该放在checkpoints/srdiff_pretrained_div2k/目录下的
  
您好，论文中讲的celeba总共训练30k次，预训练模型直接就是30k次呢，所以这个是不用预训练模型还是把总训练次数改成60k次呀？
  
Traceback (most recent call last):
 File "D:\anaconda_path\envs\basicsr\lib\runpy.py", line 192, in _run_module_as_main
 return _run_code(code, main_globals, None,
 File "D:\anaconda_path\envs\basicsr\lib\runpy.py", line 85, in _run_code
 exec(code, run_globals)
 File "F:\SRDiff-main\tasks\trainer.py", line 248, in 
 trainer.train()
 File "F:\SRDiff-main\tasks\trainer.py", line 57, in train
 model = self.build_model()
 File "F:\SRDiff-main\tasks\srdiff.py", line 13, in build_model
 hidden_size = hparams['hidden_size']
 KeyError: 'hidden_size'
 你好~你碰到这个问题了吗？可否请教一下？
