### ISSUE TITLE
Can not re-produce SR result on DIV2K dataset

### ISSUE THREAD

**Issue by Arcananana** [LeiaLi/SRDiff#14]
Thanks for your work. When I try to re-produce the SR results using the pre-trained models, the reconstructed images contains lots of noises like this 
![0801 SR](https://github.com/LeiaLi/SRDiff/assets/49430025/e917a656-98f9-4e0b-872c-6d55d0237ab2)
{'psnr': 14.266, 'ssim': 0.115, 'lpips': 1.334, 'lr_psnr': 25.924} total: 1

**Comment by 2590609710** [comment]
> 谢谢你的工作。当我尝试使用预先训练的模型重新生成 SR 结果时，重建的图像包含大量噪声，例如 ![0801 SR](https://user-images.githubusercontent.com/49430025/253797055-e917a656-98f9-4e0b-872c-6d55d0237ab2.png) {'psnr'： 14.266， 'ssim'： 0.115， 'lpips'： 1.334， 'lr_psnr'： 25.924} 总计： 1

Hello, I also encountered the same problem. May I ask how did you solve this issue?

**Comment by 2590609710** [comment]
> Thanks for your work. When I try to re-produce the SR results using the pre-trained models, the reconstructed images contains lots of noises like this ![0801 SR](https://user-images.githubusercontent.com/49430025/253797055-e917a656-98f9-4e0b-872c-6d55d0237ab2.png) {'psnr': 14.266, 'ssim': 0.115, 'lpips': 1.334, 'lr_psnr': 25.924} total: 1

Hello, I also encountered the same problem. May I ask how did you solve this issue?

**Comment by Ecnu-luobote** [comment]
The pre-model file should be in the checkpoints/srdiff_pretrained_div2k folder

**Comment by duanpanjun** [comment]
> The pre-model file should be in the checkpoints/srdiff_pretrained_div2k folder预模型文件应位于 checkpoints/srdiff_pretrained_div2k 文件夹中

This is what I did, but the results still contain a lot of noise. I don't understand why this is happening.

**Comment by iF1844680954** [comment]
I also encountered the same problem,Could you please tell me how you solved it？

**Comment by iF1844680954** [comment]
It seems I've solved this issue. I made the "binary_data_dir" in" configs/config_base.yaml" and "configs/df2k4x.yaml" consistent, setting the path to "binary_data_dir: data/binary/df2k4x", and then reran python :"data_gen/df2k.py". When testing, please use the terminal command:" python tasks/trainer.py --config configs/diffsr_df2k4x.yaml --exp_name srdiff_pretrained_div2k --infer."

**Comment by iF1844680954** [comment]
> I also encountered the same problem,Could you please tell me how you solved it？

It seems I've solved this issue. I made the "binary_data_dir" in" configs/config_base.yaml" and "configs/df2k4x.yaml" consistent, setting the path to "binary_data_dir: data/binary/df2k4x", and then reran python :"data_gen/df2k.py". When testing, please use the terminal command:" python tasks/trainer.py --config configs/diffsr_df2k4x.yaml --exp_name srdiff_pretrained_div2k --infer."

**Comment by SureT-T** [comment]
> > I also encountered the same problem,Could you please tell me how you solved it？
> 
> It seems I've solved this issue. I made the "binary_data_dir" in" configs/config_base.yaml" and "configs/df2k4x.yaml" consistent, setting the path to "binary_data_dir: data/binary/df2k4x", and then reran python :"data_gen/df2k.py". When testing, please use the terminal command:" python tasks/trainer.py --config configs/diffsr_df2k4x.yaml --exp_name srdiff_pretrained_div2k --infer."

Traceback (most recent call last):
  File "tasks/trainer.py", line 247, in <module>
    trainer = getattr(importlib.import_module(pkg), cls_name)()
  File "/root/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tasks'请问你有没有遇到这个问题？是如何解决的？

**Comment by iF1844680954** [comment]
> > > 我也遇到了同样的问题，能不能请告诉我你是怎么解决的呢？
> > 
> > 
> > 看来我已经解决了这个问题。我把 configs/config_base.yaml“ 和 ”configs/df2k4x.yaml“ 中的 ”binary_data_dir“ 保持一致，将路径设置为 ”binary_data_dir： data/binary/df2k4x“，然后重新运行 python ：”data_gen/df2k.py”。测试时，请使用终端命令：“ python tasks/trainer.py --config configs/diffsr_df2k4x.yaml --exp_name srdiff_pretrained_div2k --infer。
> 
> 回溯（最近调用最后一次）：文件 “tasks/trainer.py”，第 247 行，在 trainer = getattr（importlib.import_module（pkg）， cls_name）（） 文件“/root/miniconda3/lib/python3.8/importlib/**init**.py”，第 127 行，import_module返回 _bootstrap._gcd_import（name[level：]， package， level） 文件 “”，第 1014 行，_gcd_import 文件 “”中，第 991 行，_find_and_load文件 “”中，第 961 行，_find_and_load_unlocked文件 “”， 第 219 行， 在 _call_with_frames_removed 文件 “”， 第 1014 行， _gcd_import文件 “”， 第 991 行， 在 _find_and_load 文件 “”， 第 973 行， _find_and_load_unlocked ModuleNotFoundError： No module named 'tasks'请问你有没有遇到这个问题？是如何解决的？
请确保正确的--config配置，或者提供更为完整的打印信息，比如打印的路径信息

**Comment by iF1844680954** [comment]
> > > I also encountered the same problem,Could you please tell me how you solved it？
> > 
> > 
> > It seems I've solved this issue. I made the "binary_data_dir" in" configs/config_base.yaml" and "configs/df2k4x.yaml" consistent, setting the path to "binary_data_dir: data/binary/df2k4x", and then reran python :"data_gen/df2k.py". When testing, please use the terminal command:" python tasks/trainer.py --config configs/diffsr_df2k4x.yaml --exp_name srdiff_pretrained_div2k --infer."
> 
> Traceback (most recent call last): File "tasks/trainer.py", line 247, in trainer = getattr(importlib.import_module(pkg), cls_name)() File "/root/miniconda3/lib/python3.8/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1014, in _gcd_import File "", line 991, in _find_and_load File "", line 961, in _find_and_load_unlocked File "", line 219, in _call_with_frames_removed File "", line 1014, in _gcd_import File "", line 991, in _find_and_load File "", line 973, in _find_and_load_unlocked ModuleNotFoundError: No module named 'tasks'请问你有没有遇到这个问题？是如何解决的？

请确保正确的--config配置，或者提供更为完整的打印信息，比如打印的路径信息
