### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by d-linlin** [LeiaLi/SRDiff#20]
Traceback (most recent call last):
  File "tasks/trainer.py", line 9, in <module>
    from utils.hparams import hparams, set_hparams
ModuleNotFoundError: No module named 'utils'

请问怎么解决呀

**Comment by Philcalab** [comment]
> Traceback (most recent call last): File "tasks/trainer.py", line 9, in from utils.hparams import hparams, set_hparams ModuleNotFoundError: No module named 'utils'
> 
> 请问怎么解决呀

我也是

**Comment by xiaodu-1** [comment]
遇到这种问题的朋友可以把需要引用的文件直接复制到同一目录下

**Comment by PQRMQM** [comment]
给每个文件夹一个__init__.py文件，再把python task/xxx.py换成python -m task.xxx 就行了
