### ISSUE TITLE
infer时候报错：ModuleNotFoundError: No module named 'tasks'

### ISSUE THREAD

**Issue by jp0215** [LeiaLi/SRDiff#27]
有无大佬有类似的问题。最开始碰到无法import utils的问题，后来把utils这个文件夹放到了每一个文件夹下，然后可以运行infer部分了，出现了部分配置参数，然后接着报这个错，这是为什么呢？
Traceback (most recent call last):
  File "tasks/trainer.py", line 248, in <module>
    trainer = getattr(importlib.import_module(pkg), cls_name)()
  File "-------/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tasks'
![image](https://github.com/user-attachments/assets/9ff0025e-6b87-49ea-a6cc-0d9f88d2faa8)

**Comment by xuxuduoduomeiGithub** [comment]
Traceback (most recent call last):
  File "D:\anaconda_path\envs\basicsr\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda_path\envs\basicsr\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\SRDiff-main\tasks\trainer.py", line 248, in <module>
    trainer.train()
  File "F:\SRDiff-main\tasks\trainer.py", line 57, in train
    model = self.build_model()
  File "F:\SRDiff-main\tasks\srdiff.py", line 13, in build_model
    hidden_size = hparams['hidden_size']
KeyError: 'hidden_size'
你那个我也碰到了，不知道咋解决的，后面就碰到了另外的问题，太难了~

**Comment by SureT-T** [comment]
请问解决这个问题了吗
